server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  server-header: hub-coupa-connector
management:
  endpoints:
    web.base-path: /
