server:
  compression:
     enabled: true
     mime-types: application/json,application/xml,text/html,text/xml,text/plain
  server-header: hub-salesforce-connector

sf:
  soqlQueryPath: services/data/v44.0/query
  workflowPath: services/data/v44.0/process/approvals/

management:
  endpoints:
    web.base-path: /

# The below are optional custom fields which can be configured to be used for salesforce discount workflow approval.
custom-fields:
  discount-percentage:
  reason-for-discount:
